In [1]:
import numpy as np
import pandas as pd
from scipy import stats

In [2]:
# loading the data
sb_data = pd.read_csv(r"superbowl.csv")
sb_data.tail()

Super Bowl Coin Toss Outcome Coin Toss Winner Game Winner
50          51             Tails        Home Team   Away Team
51          52             Heads        Home Team   Away Team
52          53             Tails        Home Team   Away Team
53          54             Tails        Away Team   Home Team
54          55             Heads        Away Team   Home Team

In [3]:
sb_data["Coin Toss Winner"].value_counts()


Coin Toss Winner
Away Team    30
Home Team    25
Name: count, dtype: int64

In [4]:
sb_data["Game Winner"].value_counts()

Game Winner
Away Team    31
Home Team    24
Name: count, dtype: int64

In [5]:
coin_tost_counts=sb_data["Coin Toss Outcome"].value_counts()

In [6]:
fair_coin_expected=[sum(coin_tost_counts)/2,sum(coin_tost_counts)/2]
fair_coin_expected

[27.5, 27.5]

In [7]:
fair_coin_observed=coin_tost_counts.values
fair_coin_observed

array([29, 26])

In [8]:
#testing whether its a fair coin
fair_coin_result=stats.chisquare(fair_coin_observed,fair_coin_expected)
fair_coin_result

Power_divergenceResult(statistic=np.float64(0.16363636363636364), pvalue=np.float64(0.6858304344516056))

In [9]:
gamewinner_counts=sb_data["Game Winner"].value_counts()
gamewinner_counts

Game Winner
Away Team    31
Home Team    24
Name: count, dtype: int64

In [10]:
observed=gamewinner_counts.values
observed

array([31, 24])

In [11]:
expected=[sum(gamewinner_counts)/2,sum(gamewinner_counts)/2]
expected

[27.5, 27.5]

In [12]:
results=stats.chisquare(observed,expected)
results

Power_divergenceResult(statistic=np.float64(0.8909090909090909), pvalue=np.float64(0.34523107177184))

In [13]:
nfl_games= pd.read_csv(r"nfl_games.csv")
nfl_games.head()

date  season  neutral  playoff team1 team2      elo1      elo2  \
0  1920-09-26    1920        0        0   RII   STP  1503.947  1300.000   
1  1920-10-03    1920        0        0   AKR   WHE  1503.420  1300.000   
2  1920-10-03    1920        0        0   RCH   ABU  1503.420  1300.000   
3  1920-10-03    1920        0        0   DAY   COL  1493.002  1504.908   
4  1920-10-03    1920        0        0   RII   MUN  1516.108  1478.004   

   elo_prob1  score1  score2  result1  
0   0.824651      48       0      1.0  
1   0.824212      43       0      1.0  
2   0.824212      10       0      1.0  
3   0.575819      14       0      1.0  
4   0.644171      45       0      1.0

In [14]:
nfl_games = nfl_games[(nfl_games["neutral"] == 0) & (nfl_games["playoff"] == 0) & (nfl_games["season"] >= 1966 )]
# Engineer a new feature
nfl_games.loc[nfl_games["result1"] == 0, "Game Winner"] = "Away Team"
nfl_games.loc[nfl_games["result1"] == 1, "Game Winner"] = "Home Team"

game_winner_counts_nfl = nfl_games["Game Winner"].value_counts().sort_index()
game_winner_counts_nfl

Game Winner
Away Team    5265
Home Team    7066
Name: count, dtype: int64

In [15]:
nfl_observed= game_winner_counts_nfl.values
nfl_observed

array([5265, 7066])

In [16]:
nfl_expected= [sum(game_winner_counts_nfl)/2,sum(game_winner_counts_nfl)/2]
nfl_expected

[6165.5, 6165.5]

In [17]:
nfl_chisquare= stats.chisquare(nfl_observed,nfl_expected)
nfl_chisquare

Power_divergenceResult(statistic=np.float64(263.0444408401589), pvalue=np.float64(3.723190824055013e-59))

In [18]:
independence_table = pd.crosstab(sb_data["Coin Toss Winner"], sb_data["Game Winner"])
independence_table

Game Winner       Away Team  Home Team
Coin Toss Winner                      
Away Team                15         15
Home Team                16          9

In [19]:
chi2,p,dof,exf=stats.chi2_contingency(independence_table)
print(chi2,p,dof,exf)

0.5920138888888885 0.44164141533080714 1 [[16.90909091 13.09090909]
 [14.09090909 10.90909091]]
