####  File input/output
with statement---is used in file handling in python to avoid forgetting to close the file


In [ ]:
-

In [12]:
with open("sample.txt","w") as file:
  file.write("Hello World!")

In [13]:
with open("sample.txt","r") as file:
  content= file.read()
  print(content)

Hello World!


In [14]:
with open("Excel_jumia 1.csv","r") as file:
  content=file.read()
  print(content)

Product,Current price,old price,Discount,Review,Ratingd
115  Piece Set Of Multifunctional Precision Screwdrivers,KSh 950,"KSh 1,525",38%,-2,4.5 out of 5
Metal Decorative Hooks Key Hangers Entryway Wall Hooks Towel Hooks - Home,KSh 527,KSh 999,47%,-14,4.1 out of 5
Portable Mini Cordless Car Vacuum Cleaner - Blue,"KSh 2,199","KSh 2,923",25%,-24,4.6 out of 5
Weighing Scale Digital Bathroom Body Fat Scale USB-Black,"KSh 1,580","KSh 2,499",37%,-7,4.7 out of 5
Portable Home Small Air Humidifier 3-Speed Fan - Green,"KSh 1,740","KSh 2,356",26%,-5,4.8 out of 5
"220V 60W Electric Soldering Iron Kits With Tools, Tips, And Multimeter","KSh 2,999","KSh 3,290",9%,-15,4 out of 5
137 Pieces Cake Decorating Tool Set Baking Supplies,"KSh 2,319","KSh 3,032",24%,-55,4.6 out of 5
Desk Foldable Fan Adjustable Fan Strong Wind 3 Gear Usb,KSh 988,"KSh 1,580",37%,-2,4 out of 5
LASA FOLDING TABLE SERVING STAND,"KSh 1,274","KSh 2,800",55%,-5,4.8 out of 5
13 In 1 Home Repair Tools Box Kit Set,"KSh 1,600","KSh 2,92

In [14]:
import pandas as pd
df=pd.read_csv(r"Excel_jumia 1.csv")
df.head()

Product Current price  old price  \
0  115  Piece Set Of Multifunctional Precision Sc...       KSh 950  KSh 1,525   
1  Metal Decorative Hooks Key Hangers Entryway Wa...       KSh 527    KSh 999   
2   Portable Mini Cordless Car Vacuum Cleaner - Blue     KSh 2,199  KSh 2,923   
3  Weighing Scale Digital Bathroom Body Fat Scale...     KSh 1,580  KSh 2,499   
4  Portable Home Small Air Humidifier 3-Speed Fan...     KSh 1,740  KSh 2,356   

  Discount  Review       Ratingd  
0      38%    -2.0  4.5 out of 5  
1      47%   -14.0  4.1 out of 5  
2      25%   -24.0  4.6 out of 5  
3      37%    -7.0  4.7 out of 5  
4      26%    -5.0  4.8 out of 5

In [16]:
df.to_csv("sample.csv", index=False)

Pandas is a powerful library for data analysis and is used to manipulate data sets
provides 2 main data structures 
-series...like a column
-Data frame...Table


In [17]:
#loading the dataset
df=pd.read_csv(r"Excel_jumia 1.csv")
df.tail(10) #for the last 10
#df.head

Product Current price  \
105  9pcs Gas Mask, For Painting, Dust, Formaldehyd...     KSh 1,420   
106  24 Grid Wall-mounted Sundries Organiser Fabric...     KSh 1,875   
107      1PC Refrigerator Food Seal Pocket Fridge Bags       KSh 198   
108                 LED Solar Street Light-fake Camera     KSh 1,150   
109  Cartoon Embroidered Mini Towel Bear Cotton Was...     KSh 1,190   
110  Shower Nozzle Cleaning Unclogging Needle Mini ...     KSh 1,658   
111  Thickening Multipurpose Non Stick Easy To Clea...     KSh 1,768   
112  6 In 1 Bottle Can Opener Multifunctional Easy ...       KSh 199   
113         Wall-mounted Sticker Punch-free Plug Fixer       KSh 450   
114  Black Simple Water Cup Wine Coaster Anti Slip ...       KSh 169   

     old price Discount  Review     Ratingd  
105  KSh 2,420      41%     NaN         NaN  
106  KSh 1,899       1%     NaN         NaN  
107    KSh 260      24%     NaN         NaN  
108  KSh 1,737      34%     NaN         NaN  
109  KSh 1,810      34%     NaN         NaN  
110  KSh 1,699       2%     NaN         NaN  
111  KSh 1,799       2%     NaN         NaN  
112    KSh 553      64%     NaN         NaN  
113    KSh 900      50%    -1.0  2 out of 5  
114    KSh 320      47%     NaN         NaN

In [18]:
#view info about your data set
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 115 entries, 0 to 114
Data columns (total 6 columns):
 #   Column         Non-Null Count  Dtype  
---  ------         --------------  -----  
 0   Product        115 non-null    object 
 1   Current price  115 non-null    object 
 2   old price      115 non-null    object 
 3   Discount       115 non-null    object 
 4   Review         57 non-null     float64
 5   Ratingd        57 non-null     object 
dtypes: float64(1), object(5)
memory usage: 5.5+ KB


In [19]:
#checking for missing values
df.isnull().sum()

Product           0
Current price     0
old price         0
Discount          0
Review           58
Ratingd          58
dtype: int64

fillna method is used to fill missing values in columns

In [27]:
#to drop the two columns we can exclude the columns place in list
df=df.drop(columns=["Review","Ratingd"],axis=1)
df.head()

Product Current price  old price  \
0  115  Piece Set Of Multifunctional Precision Sc...       KSh 950  KSh 1,525   
1  Metal Decorative Hooks Key Hangers Entryway Wa...       KSh 527    KSh 999   
2   Portable Mini Cordless Car Vacuum Cleaner - Blue     KSh 2,199  KSh 2,923   
3  Weighing Scale Digital Bathroom Body Fat Scale...     KSh 1,580  KSh 2,499   
4  Portable Home Small Air Humidifier 3-Speed Fan...     KSh 1,740  KSh 2,356   

  Discount  
0      38%  
1      47%  
2      25%  
3      37%  
4      26%

In [15]:
data=pd.read_csv(r"tested.csv")
data.head()

PassengerId  Survived  Pclass  \
0          892         0       3   
1          893         1       3   
2          894         0       2   
3          895         0       3   
4          896         1       3   

                                           Name     Sex   Age  SibSp  Parch  \
0                              Kelly, Mr. James    male  34.5      0      0   
1              Wilkes, Mrs. James (Ellen Needs)  female  47.0      1      0   
2                     Myles, Mr. Thomas Francis    male  62.0      0      0   
3                              Wirz, Mr. Albert    male  27.0      0      0   
4  Hirvonen, Mrs. Alexander (Helga E Lindqvist)  female  22.0      1      1   

    Ticket     Fare Cabin Embarked  
0   330911   7.8292   NaN        Q  
1   363272   7.0000   NaN        S  
2   240276   9.6875   NaN        Q  
3   315154   8.6625   NaN        S  
4  3101298  12.2875   NaN        S

In [30]:
data.groupby("Pclass")["Fare"].sum()

Pclass
1    10087.9918
2     2064.7957
3     2703.7501
Name: Fare, dtype: float64

#### Numpy-Numerical Python
is a fast efficient library for computing
provides a high performance array object and tools to work with 
numpy array-


In [1]:
numbers= [1,2,3,4,5,6,7,8,9,10]
nums=[10,9,8,7,6,5,4,3,2,1]
add1= numbers+nums
print(add1)

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 10, 9, 8, 7, 6, 5, 4, 3, 2, 1]


In [3]:
import numpy as np

In [4]:
numbers_array=np.array(numbers)
numbers_array

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [5]:
nums_array=np.array(nums)
nums_array

array([10,  9,  8,  7,  6,  5,  4,  3,  2,  1])

In [7]:
add2=numbers_array+nums_array
add2

array([11, 11, 11, 11, 11, 11, 11, 11, 11, 11])

In [8]:
numbers_array.mean()

np.float64(5.5)

In [9]:
numbers_array.sum()

np.int64(55)

In [10]:
numbers_array.std()

np.float64(2.8722813232690143)

In [11]:
numbers_array.var()

np.float64(8.25)